version: '3.9'
services:
  syncmiru:
    image: syncmiru:dev
    container_name: syncmiru
    volumes:
      - ./config:/config
    ports:
      - '8282:8282'
  postgres:
    container_name: SyncMiru-postgres
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=SyncMiru
      - POSTGRES_PASSWORD=SyncMiru
    ports:
      - '5434:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    driver: local